### ISSUE TITLE
青龙面板执行脚本出错

### ISSUE THREAD

**Issue by 1029237703** [Oreomeow/checkinpanel#106]
## 开始执行... 2022-02-23 17:32:28

尝试检查运行环境...
成功，当前环境为: 青龙面板。
环境检查结束。

配置文件 (notify.toml) 检查开始...
在 /ql/config/notify.toml 发现配置文件。
配置文件检查结束。

通知配置文件存在：/ql/config/notify.toml。
checkinpanel 当前版本：20220213-4-013，不在 8-12 点内，跳过版本检查。

配置文件 (check.toml) 检查开始...
在 /ql/config/check.toml 发现配置文件。
配置文件检查结束。

Traceback (most recent call last):
  File "/ql/scripts/Oreomeow_checkinpanel_master/ck_epic.py", line 1677, in <module>
    start()
  File "/ql/scripts/Oreomeow_checkinpanel_master/ck_epic.py", line 1672, in start
    res = run(args, check_items=_check_items)
  File "/ql/scripts/Oreomeow_checkinpanel_master/ck_epic.py", line 1647, in run
    claimed_item_titles = main(args, raise_error=True)
  File "/ql/scripts/Oreomeow_checkinpanel_master/ck_epic.py", line 1554, in main
    claimer = EpicgamesClaimer(
  File "/ql/scripts/Oreomeow_checkinpanel_master/ck_epic.py", line 406, in __init__
    self.open_browser()
  File "/ql/scripts/Oreomeow_checkinpanel_master/ck_epic.py", line 1257, in open_browser
    return self._loop.run_until_complete(self._open_browser_async())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/ql/scripts/Oreomeow_checkinpanel_master/ck_epic.py", line 454, in _open_browser_async
    self.browser = await launch(
  File "/usr/lib/python3.9/site-packages/pyppeteer/launcher.py", line 307, in launch
    return await Launcher(options, **kwargs).launch()
  File "/usr/lib/python3.9/site-packages/pyppeteer/launcher.py", line 148, in launch
    self.proc = subprocess.Popen(  # type: ignore
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chromium-browser'

## 执行结束... 2022-02-23 17:32:33 耗时 4 秒

签到依赖脚本已经安装完毕 这是什么情况

**Comment by night-raise** [comment]
@1029237703 先执行 ins_selenium.sh 或者相关任务。

**Comment by 1029237703** [comment]
## 开始执行... 2022-02-25 16:21:31

fetch https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.15/main/aarch64/APKINDEX.tar.gz
fetch https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.15/community/aarch64/APKINDEX.tar.gz
v3.15.0-311-g0a14a1ab9a [https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.15/main]
v3.15.0-312-g1f7838f063 [https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.15/community]
OK: 15733 distinct packages available
bash 已安装
curl 已安装
gcc 已安装
git 已安装
jq 已安装
libffi-dev 已安装
make 已安装
musl-dev 已安装
openssl-dev 已安装
perl 已安装
perl-app-cpanminus 已安装
perl-dev 已安装
py3-pip 已安装
python3 已安装
python3-dev 已安装
wget 已安装
Requirement already satisfied: pip in /usr/lib/python3.9/site-packages (22.0.3)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
bs4 已安装
cryptography 已安装
dateparser 已安装
feedparser 已安装
peewee 已安装
pyaes 已安装
pyppeteer 已安装
requests 已安装
rsa 已安装
schedule 已安装
tomli 已安装

up to date in 8s
@iarna/toml 已正确安装
axios 已正确安装
crypto-js 已正确安装
got 已正确安装
checkinpanel@1.0.0 /ql/scripts/Oreomeow_checkinpanel_master
├── @iarna/toml@2.2.5
├── axios@0.23.0
├── crypto-js@4.1.1
└── got@11.8.3

App::cpm 已安装
File::Slurp 已安装
JSON5 已安装
TOML::Dumper 已安装

## 执行结束... 2022-02-25 16:23:49 耗时 138 秒

**Comment by Oreomeow** [comment]
该脚本已失效，暂不维护，可寻找其他 epic 代替项目
