### ISSUE TITLE
众多脚本只有吾爱破解的报错，求大佬解答

### ISSUE THREAD

**Issue by 1768335959** [Oreomeow/checkinpanel#111]
配置文件 (notify.toml) 检查开始...
在 /ql/config/notify.toml 发现配置文件。
配置文件检查结束。

通知配置文件存在：/ql/config/notify.toml。
checkinpanel 当前版本：20220313-4-010，最新版本：20220313-4-010

配置文件 (check.toml) 检查开始...
在 /ql/config/check.toml 发现配置文件。

配置文件检查结束。

Traceback (most recent call last):
  File "/ql/scripts/Oreomeow_checkinpanel_master/ck_pojie.py", line 59, in <module>
    res = Pojie(check_items=_check_items).main()
  File "/ql/scripts/Oreomeow_checkinpanel_master/ck_pojie.py", line 49, in main
    sign_msg = self.sign(cookie=cookie)
  File "/ql/scripts/Oreomeow_checkinpanel_master/ck_pojie.py", line 33, in sign
    fc = fb.find("div", id="messagetext").find("p").text
AttributeError: 'NoneType' object has no attribute 'find'

- ## 执行结束... 2022-03-19 11:20:56 耗时 2 ### 
![捕获](https://user-images.githubusercontent.com/74478906/159105584-4380fad4-72ad-42fb-97ce-4f212ce30bcd.PNG)

**Comment by 1768335959** [comment]
依赖都装过了，和旧机子一样，旧机子可以签到成功，这个不行

**Comment by Oreomeow** [comment]
重新抓 cookie
