### ISSUE TITLE
什么值得买任务版js的ck错误。

### ISSUE THREAD

**Issue by LIUTQ28** [Oreomeow/checkinpanel#131]
什么值得买

没有读取到什么值得买有效cookie，请访问zhiyou.smzdm.com进行登录

GitHub: https://github.com/Oreomeow/checkinpanel

根据配置文件里设置好ck，py的签到每天正常，任务版js提示报错。

**Comment by Oreomeow** [comment]
尝试重抓，我这里运行正常

**Comment by LIUTQ28** [comment]
> 尝试重抓，我这里运行正常

我是按照配置文件要求的 
 ​cookie​ = ​"​sess=xxxxxx;​"
只填写了sess，是我填写的不完整吗？
如果ck失效的话py应该也报错，但是报错的只有 js，py签到还在正常运行。

**Comment by Oreomeow** [comment]
@LIUTQ28 __xkguid=xxxxxxxxxxxxxxxxxxxxxxx; 
r_sort_type=xxxxx; 
__jsluid_s=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; 
smzdm_user_source=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; 
device_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; 
homepage_sug=c; 
_zdmA.uid=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; 
_zdmA.vid=x; 
footer_floating_layer=x; 
ad_date=xx; 
bannerCounter=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; 
ad_json_feed=xxxxxx; 
_zdmA.time=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; 
sess=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; 
user=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; 
smzdm_id=xxxxxxxxxx;

**Comment by LIUTQ28** [comment]
@Oreomeow 
按照你给的CK模板我重新写了一下配置，JS,PY全部报错了
bannerCounter里面有双引号我按照配置提示改成单引号也是报错，无论单双都是报错。抓取的CK源是__ckguid，老大给的的XK改成了__xkguid和__ckguid都试过也是报错，莫非是我抓的问题？
但是我反复试了好几次。
－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－
您使用的是自己的通知配置文件。
自动寻找配置文件 toml 解析失败，错误信息： TomlError: Unknown character "60" at row 8, col 1, pos 8:
 7: 
 8> <!DOCTYPE html>
    ^
 9: <html lang="en" data-color-mode="auto" data-light-theme="light" data-dark-theme="dark" data-a11y-animated-images="system">


    at TOMLParser.parseStart (/ql/data/scripts/Oreomeow_checkinpanel_master/node_modules/@iarna/toml/lib/toml-parser.js:297:26)
    at TOMLParser.runOne (/ql/data/scripts/Oreomeow_checkinpanel_master/node_modules/@iarna/toml/lib/parser.js:64:30)
    at TOMLParser.parse (/ql/data/scripts/Oreomeow_checkinpanel_master/node_modules/@iarna/toml/lib/parser.js:45:22)
    at Object.parseString [as parse] (/ql/data/scripts/Oreomeow_checkinpanel_master/node_modules/@iarna/toml/parse-string.js:13:12)
    at getData (/ql/data/scripts/Oreomeow_checkinpanel_master/utils.js:8:791)
    at Object.<anonymous> (/ql/data/scripts/Oreomeow_checkinpanel_master/ck_smzdm.js:14:23)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12) {
  fromTOML: true,
  wrapped: null,
  line: 7,
  col: 0,
  pos: 8
}

**Comment by LIUTQ28** [comment]
错误：配置文件 /ql/data/config/check.toml 格式不对，请学习 https://toml.io/cn/v1.0.0
错误信息：
Traceback (most recent call last):
  File "/ql/data/scripts/Oreomeow_checkinpanel_master/utils.py", line 37, in get_data
    DATA = tomli.load(open(check_config, "rb"))
  File "/usr/lib/python3.10/site-packages/tomli/_parser.py", line 66, in load
    return loads(s, parse_float=parse_float)
  File "/usr/lib/python3.10/site-packages/tomli/_parser.py", line 102, in loads
    pos = key_value_rule(src, pos, out, header, parse_float)
  File "/usr/lib/python3.10/site-packages/tomli/_parser.py", line 326, in key_value_rule
    pos, key, value = parse_key_value_pair(src, pos, parse_float)
  File "/usr/lib/python3.10/site-packages/tomli/_parser.py", line 369, in parse_key_value_pair
    pos, value = parse_value(src, pos, parse_float)
  File "/usr/lib/python3.10/site-packages/tomli/_parser.py", line 598, in parse_value
    return parse_one_line_basic_str(src, pos)
  File "/usr/lib/python3.10/site-packages/tomli/_parser.py", line 409, in parse_one_line_basic_str
    return parse_basic_str(src, pos, multiline=False)
  File "/usr/lib/python3.10/site-packages/tomli/_parser.py", line 580, in parse_basic_str
    raise suffixed_err(src, pos, f"Illegal character {char!r}")
tomli.TOMLDecodeError: Illegal character '\n' (at line 283, column 116)


## 执行结束... 2022-06-30 11:04:47 耗时 1 秒

**Comment by Oreomeow** [comment]
@LIUTQ28 换行符删了

**Comment by LIUTQ28** [comment]
还是一样的错误，所有的空格换行符都删掉了。 填写内容如下。 我是真的被搞迷糊了
```
 什么值得买
# https://www.smzdm.com cookie
[[SMZDM]]
cookie = "__xkguid=xxxxxxxxxxxxxxxxxxxxxxx; r_sort_type=xxxxx; __jsluid_s=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; smzdm_user_source=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; device_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; homepage_sug=c; _zdmA.uid=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; _zdmA.vid=x; footer_floating_layer=x; ad_date=xx; bannerCounter=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; ad_json_feed=xxxxxx; _zdmA.time=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; sess=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; user=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; smzdm_id=xxxxxxxxxx;"
```

其中bannerCounter里面有双引号“”，我试了三种转义，以及不转义，都是报错。

```
您使用的是自己的通知配置文件。
自动寻找配置文件 toml 解析失败，错误信息： TomlError: Unknown character "60" at row 8, col 1, pos 8:
 7: 
 8> <!DOCTYPE html>
    ^
 9: <html lang="en" data-color-mode="auto" data-light-theme="light" data-dark-theme="dark" data-a11y-animated-images="system">


    at TOMLParser.parseStart (/ql/data/scripts/Oreomeow_checkinpanel_master/node_modules/@iarna/toml/lib/toml-parser.js:297:26)
    at TOMLParser.runOne (/ql/data/scripts/Oreomeow_checkinpanel_master/node_modules/@iarna/toml/lib/parser.js:64:30)
    at TOMLParser.parse (/ql/data/scripts/Oreomeow_checkinpanel_master/node_modules/@iarna/toml/lib/parser.js:45:22)
    at Object.parseString [as parse] (/ql/data/scripts/Oreomeow_checkinpanel_master/node_modules/@iarna/toml/parse-string.js:13:12)
    at getData (/ql/data/scripts/Oreomeow_checkinpanel_master/utils.js:8:791)
    at Object.<anonymous> (/ql/data/scripts/Oreomeow_checkinpanel_master/ck_smzdm.js:14:23)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12) {
  fromTOML: true,
  wrapped: null,
  line: 7,
  col: 0,
  pos: 8
}
```
