### ISSUE TITLE
Glados大家都有错误吗

### ISSUE THREAD

**Issue by catseie** [Oreomeow/checkinpanel#134]
GLaDOS

--------------------
Msg: Check in error!
Error:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ql/data/scripts/Oreomeow_checkinpanel_master/ck_glados.py", line 93, in main
    check_in_response = self.api_check_in(cookie)
  File "/ql/data/scripts/Oreomeow_checkinpanel_master/ck_glados.py", line 58, in api_check_in
    return r.json()
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] <!DOCTYPE HTML>
<html lang="en-US">
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
  <meta name="robots" content="noindex, nofollow" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>Just a moment...</title>
  <style>
    html, body {width: 100%; height: 100%; margin: 0; padding: 0;}
    body {background-color: #ffffff; color: #000000; font-family:-apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, "Helvetica Neue",Arial, sans-serif; font-size: 16px; line-height: 1.7em;-webkit-font-smoothing: antialiased;}
    h1 { text-align: center; font-weight:700; margin: 16px 0; font-size: 32px; color:#000000; line-height: 1.25;}
    p {font-size: 20px; font-weight: 400; margin: 8px 0;}
    p, .attribution, {text-align: center;}
    #spinner {margin: 0 auto 30px auto; display: block;}
    .attribution {margin-top: 32px;}
    @keyframes fader     { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
    @-webkit-keyframes fader { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
    #cf-bubbles > .bubbles { animation: fader 1.6s infinite;}
    #cf-bubbles > .bubbles:nth-child(2) { animation-delay: .2s;}
    #cf-bubbles > .bubbles:nth-child(3) { animation-delay: .4s;}
    .bubbles { background-color: #f58220; width:20px; height: 20px; margin:2px; border-radius:100%; display:inline-block; }
    a { color: #2c7cb0; text-decoration: none; -moz-transition: color 0.15s ease; -o-transition: color 0.15s ease; -webkit-transition: color 0.15s ease; transition: color 0.15s ease; }
    a:hover{color: #f4a15d}
    .attribution{font-size: 16px; line-height: 1.5;}
    .ray_id{display: block; margin-top: 8px;}
    #cf-wrapper #challenge-form { padding-top:25px; padding-bottom:25px; }
    #cf-hcaptcha-container { text-align:center;}
    #cf-hcaptcha-container iframe { display: inline-block;}
  </style>

      <meta http-equiv="refresh" content="35">
  <script>
    //<![CDATA[
    (function(){
      window._cf_chl_opt={
        cvId: "2",
        cType: "non-interactive",
        cNounce: "30155",
        cRay: "72809b729cea5b10",
        cHash: "283570c2f898d51",
        cUPMDTk: "\/api\/user\/checkin?__cf_chl_tk=wLtI978y6_zzW.Pdcpx5Ju_FMPZPJ0TDUusTgp8uCkU-1657364964-0-gaNycGzNCj0",
        cFPWv: "g",
        cTTimeMs: "1000",
        cRq: {
          ru: "aHR0cHM6Ly9nbGFkb3Mucm9ja3MvYXBpL3VzZXIvY2hlY2tpbg==",
          ra: "TW96aWxsYS81LjAgKE1hY2ludG9zaDsgSW50ZWwgTWFjIE9TIFggMTBfMTVfNykgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzkxLjAuNDQ3Mi4xMTQgU2FmYXJpLzUzNy4zNg==",
          rm: "UE9TVA==",
          d: "ZOQ9oyRjNQ0+93V87hztTqmYsv08sTQptQGOJfVmUIR/wMQnVNdnmr/G25UARkYPLFgXKt/WH3c9cIxRtU7azm+a/TAPD/AH608yRqnCjTeeiIc6q8wRk5wXYEunHWzcpmxwwBLXf53pP/wgdYJZ/xkrDJpjvQIcJHhTEX0SKUeCNUmNzGJzLY2dV5HzN7gDUC3909wif/nqLkUFP3OdNeXSHDFdFIrvFtrAGal5aSDGpzJzpVq/zQeqsms/h5vHGSdeVm3hfSD6VFklJ2RhH45m12sUd+ltw7muVRJaSPbfh2f1mYvugM76fUk0G3sOlrRltguDEBttiI6b/QN+TdSi+8vGRijVUJBHL/7gCUU5v9WUKlm0BWhl+aWTbCoo35diif86UhrYfh643qJs0KKeB2yVUGbkWmyEgU0AtrKB79xMgth8vobkrIe775oisD+SqirDqUdYXN00fBI+lpda9Wl497iOEZLBSXTPlTWgHOzZftvpb8RAOJOv+wcxO0IAxLyKOZ7t3bM1o11D+M/VZ6ycLLyK1swktS3IWxIZ25ansiOpz1uXycu9r9Ku",
          t: "MTY1NzM2NDk2NC4yNzAwMDA=",
          m: "05b1+acQQOJ2A4S4VwhUtXoDCITxpuWgYAaeMt9ed3w=",
          i1: "IdSrtYgGOmr6eXl1N8K9vg==",
          i2: "M+oBUNxYc+ShF1Zj3q29tQ==",
          zh: "vClsmK5IFAdojT0kkLQV+SlO0BEbanwG85mT3eUv5XU=",
          uh: "pDW+wMwkbkqK5qzJfhUdgJSL/IYwYPvFc78XZD/TiKw=",
          hh: "3rkrS4iP51uS9kpqMVOxDu8bYnwXul2JQhnxU/7nFv4=",
        }
      }
      window._cf_chl_enter = function(){window._cf_chl_opt.p=1};
    })();
    //]]>
  </script>
  

</head>
<body>
  <table width="100%" height="100%" cellpadding="20">
    <tr>
      <td align="center" valign="middle">
          <div class="cf-browser-verification cf-im-under-attack">
  <noscript>
    <h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1>
  </noscript>
  <div id="cf-content" style="display:none">
    
    <div id="cf-bubbles">
      <div class="bubbles"></div>
      <div class="bubbles"></div>
      <div class="bubbles"></div>
    </div>
    <h1><span data-translate="checking_browser">Checking your browser before accessing</span> glados.rocks.</h1>
    <div style="position: absolute; top: -250px; left: -250px;"><a href="https://darksoulz.us/corporeal.php?user=2">table</a></div>
    <div id="no-cookie-warning" class="cookie-warning" data-translate="turn_on_cookies" style="display:none">
      <p data-translate="turn_on_cookies" style="color:#bd2426;">Please enable Cookies and reload the page.</p>
    </div>
    <p data-translate="process_is_automatic">This process is automatic. Your browser will redirect to your requested content shortly.</p>
    <p data-translate="allow_5_secs" id="cf-spinner-allow-5-secs" >Please allow up to 5 seconds&hellip;</p>
    <p data-translate="redirecting" id="cf-spinner-redirecting" style="display:none">Redirecting&hellip;</p>
  </div>
   
  <form class="challenge-form" id="challenge-form" action="/api/user/checkin?__cf_chl_f_tk=wLtI978y6_zzW.Pdcpx5Ju_FMPZPJ0TDUusTgp8uCkU-1657364964-0-gaNycGzNCj0" method="POST" enctype="application/x-www-form-urlencoded">
    <input type="hidden" name="md" value="ZZmONfem7hRr0VSr.PVQSmO2IcrxKfoKCu0XbwEzGWs-1657364964-0-AQB8Q5msyNQrIb1E6KmRhAkZg_L3Ewmaw6qkd3cqgJBWMbNfGRElJJGWkdN7gg2HLu-TAAdjHQbA5RVKDsuSUMstvxbPqNCSgVOcRemKZ0jOek2TTT6wh3omGP_5dAPOYMx9uhbsgbkFGeWuZiJFnbrolqZ-XUMemSKqPBoqB61c8sc6QQRxfeTS3pk3NwFSOd04fXhASkzvZ45twNlXdPBe5iPEUBhThh0wpDd0qamc4xtfBgtH4yV6ZURmf7wJrTaYc_ItWYzJrHrrXLcPYKkvr_xvLmtTqPjW81edFwu_Lh5PIOlxXpgJpX05-jj3R9eWfy3gLKgIaNHpuSSgC_sYPaBKrKSmxmFqG1FZ_dCOcNg1a4jQYeW-q8zxuYofk7NhjVvxo-rUuPqsfx3PGaFtueXm8_iSt7594j9nD9IiqSTPMsfXtcVAH6SOsBdkQD1Z7WilPqMmEGRNYsYttHfB-4irR3zg8ibyX9dqarj9jJ2mP-nKLUAcrEQ75BBktSH9v71V6biXivjI0vQXbiZ8A7aMpb7jQu29AAeDZdm3rOwMlIgG0yfhye1NZ8T6v2eoxyISWsJkA-BUTajgELU" />
    <input type="hidden" name="r" value="M6zUaaChDUPD0OCACY.9YMc1X7rQReRds_3yWEAAeBg-1657364964-0-AfO9pjSr7Su75wHySB3yxh8fOFeLhj8FA/NW9tVyEpd6jW7oX0D0wNSIQt5GabJut2R7lMR3JSn87nUkWckFa0Ox45Q6TU2DaBlV1APsK5kNlH7ofOaPqt5e82ROSuT/2pxXIWO52N+pUu/jKTkGqu5GILwHH6qrG5BP8Mln1lGc2Odpvg9jaDw3aJAb70YCr7J6Ikx9TNGjYl6/w7nT+VefGfs0dDhW6w59citd9x4nhGN+FnOAIn+5ZCdglLGwmq3hyJWTUeeb9wM5DlBSL6oYh20MA0z3qI3f20jnkm3gFFM/pOBCuD1LyBFLqFSOzK/zkg69o8M7sCsiZtElbrf9mULSsxoBeqws4et3OTwkBIvJdapPv1YJEPtUP9lrAM/xhIWmH0W4vES/63SNByXxXnWX4jwKwCokZFoKBSs5yI3FuaaoJhVG+6bEoxap598UQXqOkRYNqTFElX636RbewltZm0+RtDP1FIOaUSYI5qom6S5Km8dOJM8UIpZ8vfKmouYd2EFgOxaoLgnKjM1dqBl56QWNRiFz24mMHuUMc+N+IOHzP8PPZsjqJv9l4JsOdMhGV8eQ1ngco/Uyl7VxfVs/qc7tsu0/o6H4lxHxn/oheNq11xlmth02yfW7FZFR0cfGSYCGrtH4DL8Pfc16BAIKquOSS/C3L1f5ra4BCexbTI37HidJMWyqInemluzM7Sg9wDHgLZNXuFC7nnAHH9CeXG9fW2dM+ql0uXYaZwUt5T9sUgc5SnPkdzNetBZlNyDpiDMerpwF8hrxlMX94IhWTVbIwkRDSK7DRSTH3MWK4UqjO3P8dGWvKwK9X28MP0Vhr28SVytqwQJvFI7BHdq3Qi5hzZJR+LFKG91D4Hdk+WjJCW7ayuFad/uqJuJ5onhjhtM7Nps2yEo9UBrWAmTqnX44fAZ/E6S4ji4pJIGBJXGQq9X85cYbwlV4K7x+2YWxAsNlSzE9NqlGOLWrv5eRI2VRQi/rsuQ698ZKOmro0l0iE1eDjsd0EcSQBO2+EoYkO4J9GxX1Qm8hJiIGutp+u7m7f2A1iR3AF/6U6gqmVAmGM2MXXNMltd13eOmj3E2Ozy22UbZUY5WalQYNCk1276W3K2G5d5rlb91nB7e4XxCozP/cVwerR1HtF6Sqlxay9ax0UgJA+aDAjIGaiptioE4/I/da+rB9Ve8Knm/pzz1xUJ8ETWZNNLBiXvRBtukPq41vlDg8LFzPRqx2X+q+5jqlLFzQUphw6SJo9qCb0WqbN59NB9KLbJJgNCxwlqSdQxMU6TbuuZNxntHvurM2DTb3VPpVWgiQS2fHpKMVT2TI7qdgegM2nR7lRgEpNdltV1AR6TOsRvDWxkn8wVWEBIso8jl/3mU35xblYzSDzSWmA0klxocBrQ/HDJMaLtuscpK2uPETXKRAkF/P4/ECTq6AFKFOd/oLrxzbx5wPBgPTU1oCnxPhkEi6IF10NuPmn2/LE/0mF3hfE2NemVLwtq0rW7Z7Gk5VI1BQvBUCxJASsPFNtEm5ksGqdM8K4ijIn+hYJJGu55WpUmYSww7JrgDWeVDdYHKFWVRTcjrnNYM355Nh26nCE6q8umgMj4Us1O91FHoOzabdYlS8O5gFt9Wsec4DBhOnv2Yusc0mZrZgv1m3lJdVdJCRU/DT92RYT0zbuB7qBuCWFqsAWgzPSCzaXKd4mk9+ns8y7RylimNbqJUnAfXVEGo2J4tPffYCZIIYpnd+gzEzp9QcmvbzstUP1U52ehX/BB6lFPMn+mvj+X+7EBUpUNrVloLUbk8jJvd5qMppfoQWVjfEwKLugA08Cx71Ve/j3zSR6dt2IQfaYgcMEiuNNdAoHV8wmsVgV6KXi0W2KknSmwVw98KHJXN+g+XCb3UufKcBK2gf5USzRiJ3qGKIfSBHiGi9h9MCKVUQdZ+bKL6QtScg6J+Ql35bzjEa3xpqxxiveKo6ITQj+BjrkTHkiQG4k6ZfBP/3/jmCPtzl8ETokJkluRmEsWxbtQ/KzYe3EuDkACLxFi8PjWYwiHuSAupMjHa+WAm6H5FHcuv29djYhA/weMnwcTEAbW4ncbuBcVeIOLHPzryo9NeNoCg73W4hFnd2M3pZYvIOww1lamrd3rKskC39YiL/peNyg1EWDip/muV6f6t+6CY18GC5MlOAadiA02JbtPJ5R0v3+pRanmkOEcARYj0RaCfSPIgcDhPeqvmEfy1FAlHUVBlI/gZ5rWlONUW40AXr+9AeBnfaOuBxhPCvCZ4drgcsYYDCkh6qrq8zFZ6bcqWeP5zkhM6MP/KnuDsjUzKjQLdXGwntVbkXL/jboIY++PVoZbmiejuXcvkMal3NwjbUhwEqUCX2rwaAmS5aHst0YqaP5/hM6LCljyJPH7aCPW5W0Ol5FKLSRkVRtwqCV3ryQutsthYG4PFpo9RjDu8Ya1fSoN+5Vka/jqP0eDWOrnCpRBl5HlTfl249s6l7NuNc2WO+TaP4uQbjhlu1BS7P2efzUzxADSuSgJARwR0w4UWHgmkCIetzI6u1o36fWqlCvk58yliVCw=="/>
    <input type="hidden" value="358956f013239704a22c36c2f05fd268" id="jschl-vc" name="jschl_vc"/>
    
    <input type="hidden" name="pass" value="1657364965.27-RXmrBoHoEc"/>
    <input type="hidden" id="jschl-answer" name="jschl_answer"/>
  </form>
       <script>
      //<![CDATA[
      (function(){
          var a = document.getElementById('cf-content');
          a.style.display = 'block';
          var isIE = /(MSIE|Trident\/|Edge\/)/i.test(window.navigator.userAgent);
          var trkjs = isIE ? new Image() : document.createElement('img');
          trkjs.setAttribute("src", "/cdn-cgi/images/trace/jschal/js/transparent.gif?ray=72809b729cea5b10");
          trkjs.id = "trk_jschal_js";
          trkjs.setAttribute("alt", "");
          document.body.appendChild(trkjs);
          var cpo=document.createElement('script');
          cpo.type='text/javascript';
          cpo.src="/cdn-cgi/challenge-platform/h/g/orchestrate/jsch/v1?ray=72809b729cea5b10";
          
          window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;
          window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, -window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;
          if (window._cf_chl_opt.cUPMDTk && window.history && window.history.replaceState) {
            var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;
            history.replaceState(null, null, "\/api\/user\/checkin?__cf_chl_rt_tk=wLtI978y6_zzW.Pdcpx5Ju_FMPZPJ0TDUusTgp8uCkU-1657364964-0-gaNycGzNCj0" + window._cf_chl_opt.cOgUHash);
            cpo.onload = function() {
              history.replaceState(null, null, ogU);
            };
          }
          
          document.getElementsByTagName('head')[0].appendChild(cpo);
        }());
      //]]>
    </script>

  
  <div id="trk_jschal_nojs" style="background-image:url('/cdn-cgi/images/trace/jschal/nojs/transparent.gif?ray=72809b729cea5b10')"> </div>
</div>

          
          <div class="attribution">
            DDoS protection by <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing/" target="_blank">Cloudflare</a>
            <br />
            <span class="ray_id">Ray ID: <code>72809b729cea5b10</code></span>
          </div>
      </td>
     
    </tr>
  </table>
</body>
</html>
: 0

--------------------

**Comment by Oreomeow** [comment]
https://github.com/hbstarjason/glados-checkin/issues/10

这种情况是 Glados 开启了 CF 盾导致的，后续会考虑新增一个 undetected_chromedriver 的版本
