### ISSUE TITLE
多看签到报错

### ISSUE THREAD

**Issue by cikichen** [Oreomeow/checkinpanel#138]
```python console
Traceback (most recent call last):
  File "/ql/data/scripts/Oreomeow_checkinpanel_master/ck_duokan.py", line 396, in <module>
    res = DuoKan(check_items=_check_items).main()
  File "/ql/data/scripts/Oreomeow_checkinpanel_master/ck_duokan.py", line 379, in main
    gift_msg = self.gift(cookies=cookie)
  File "/ql/data/scripts/Oreomeow_checkinpanel_master/ck_duokan.py", line 318, in gift
    msg = f"体验任务: {res.text}"
AttributeError: 'dict' object has no attribute 'text'
```

**Comment by Oreomeow** [comment]
更新 cookie 试试
