### ISSUE TITLE
葫芦侠报错

### ISSUE THREAD

**Issue by Lemonmous** [Oreomeow/checkinpanel#139]
```python console
Traceback (most recent call last):
  File "/ql/data/scripts/Oreomeow_checkinpanel_master/ck_hlx.py", line 129, in <module>
    start()
  File "/ql/data/scripts/Oreomeow_checkinpanel_master/ck_hlx.py", line 124, in start
    res = HLX(check_items=_check_items).main()
  File "/ql/data/scripts/Oreomeow_checkinpanel_master/ck_hlx.py", line 113, in main
    key, nick, userID, login_msg = self.login(username, password)
  File "/ql/data/scripts/Oreomeow_checkinpanel_master/ck_hlx.py", line 42, in login
    key = json.loads(response.text)["_key"]
KeyError: '_key'
```

**Comment by Lemonmous** [comment]
> 回溯（最后一次调用）： 文件“/ql/data/scripts/Oreomeow_checkinpanel_master/ck_hlx.py”，第 129 行，在 start() 文件“/ql/data/scripts/Oreomeow_checkinpanel_master/ck_hlx.py”，第 124 行，在开始 res = HLX(check_items=_check_items).main() 文件“/ql/data/scripts/Oreomeow_checkinpanel_master/ck_hlx.py”，第 113 行，在主 键，昵称，用户 ID，login_msg = self.login（用户名，密码) 文件“/ql/data/scripts/Oreomeow_checkinpanel_master/ck_hlx.py”，第 42 行，登录 密钥 = json.loads(response.text)["_key"] KeyError: '_key'

有大佬知道四啥问题嘛

**Comment by Oreomeow** [comment]
@Lemonmous 第一次签到吗？还是今天刚失效，测试正常
