### ISSUE TITLE
什么值得买的脚本可以合并Tsukasa007大佬的吗

### ISSUE THREAD

**Issue by WangMaoren98** [Oreomeow/checkinpanel#21]
https://github.com/Tsukasa007/my_script/blob/master/smzdm_mission.js

可完成任务如下：

点值 7/7 去购买 12/12
点赞 7/7 收藏 7/8
用户近期经验变动情况(有延迟)：
刚刚 点赞文章 +3经验值
刚刚 点赞文章 +3经验值
刚刚 收藏文章 +8经验值
刚刚 点赞文章 +3经验值
刚刚 收藏文章 +8经验值
刚刚 收藏文章 +8经验值
刚刚 点赞文章 +3经验值
刚刚 收藏文章 +8经验值
刚刚 点赞文章 +3经验值
刚刚 收藏文章 +8经验值
1分钟前 好价文章打分 +3经验值
1分钟前 好价文章打分 +3经验值
1分钟前 好价文章打分 +3经验值
1分钟前 好价文章打分 +3经验值
1分钟前 好价文章打分 +3经验值
28分钟前 每日登录 +1经验值
11小时前 昨日点击去购买奖励 +15经验值
16小时前 每日签到 +2经验值
22小时前 每日登录 +1经验值
10-03 17:46 发布评论 +10经验值

**Comment by Oreomeow** [comment]
https://github.com/Oreomeow/checkinpanel/blob/master/ck_smzdm.js
已实现

**Comment by Oreomeow** [comment]
> 多任务CK用的还是 SMZDM 那个ck么，我多任务运行了没有反应，提示完成，但是没有运行日志，也没有推送 运行在 elecv2p 上面
> 
> ```
> [schedule    info][2021-10-17 11:10:10.431] 什么值得买任务版 finished
> [checki...js info][2021-10-17 11:10:10.408] ⏳ 开始执行 ck_smzdm.js
> [schedule    info][2021-10-17 11:10:10.406] 什么值得买任务版 job start
> [funcTask    info][2021-10-17 11:10:07.406] TASK: 什么值得买任务版 started
> [schedule    info][2021-10-17 11:10:07.405] 什么值得买任务版 total countdown second: 3
> [schedule    info][2021-10-17 11:10:07.403] start schedule task: 什么值得买任务版 1/1, time: 3
> ```
![log](https://user-images.githubusercontent.com/62660101/137610598-1fa1144f-b625-4c0f-9e49-a7a9fb8c8293.png)
![log2](https://user-images.githubusercontent.com/62660101/137610600-45883a8c-23fd-4796-a060-99002984c538.png)
![log3](https://user-images.githubusercontent.com/62660101/137610692-8e02442e-59b0-436f-86b7-a1723d46c259.png)

**Comment by night-raise** [comment]
@tanmx npm install json5 你安装了吗？

**Comment by tanmx** [comment]
@night-raise 
```
[签到依赖 3  info][2021-10-17 12:21:04.118] command: npm install -g got json5 request finished
[签到依赖 3  info][2021-10-17 12:21:04.110] found 0 vulnerabilities
[签到依赖 3  info][2021-10-17 12:21:04.109] 9 packages are looking for funding
```
继续运行 张大妈做任务
```
Error: Cannot find module 'json5'
Require stack:
- /usr/local/app/script/Shell/checkinpanel/utils.js
- /usr/local/app/script/Shell/checkinpanel/ck_smzdm.js
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
at Function.Module._load (node:internal/modules/cjs/loader:778:27)
at Module.require (node:internal/modules/cjs/loader:1005:19)
at require (node:internal/modules/cjs/helpers:94:18)
at Object.<anonymous> (/usr/local/app/script/Shell/checkinpanel/utils.js:2:15)
at Module._compile (node:internal/modules/cjs/loader:1101:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Module.require (node:internal/modules/cjs/loader:1005:19) {
code: 'MODULE_NOT_FOUND',
requireStack: [
'/usr/local/app/script/Shell/checkinpanel/utils.js',
'/usr/local/app/script/Shell/checkinpanel/ck_smzdm.js'
]
}
```

**Comment by Oreomeow** [comment]
> @night-raise
> 
> ```
> [签到依赖 3  info][2021-10-17 12:21:04.118] command: npm install -g got json5 request finished
> [签到依赖 3  info][2021-10-17 12:21:04.110] found 0 vulnerabilities
> [签到依赖 3  info][2021-10-17 12:21:04.109] 9 packages are looking for funding
> ```
> 
> 继续运行 张大妈做任务
> 
> ```
> Error: Cannot find module 'json5'
> Require stack:
> - /usr/local/app/script/Shell/checkinpanel/utils.js
> - /usr/local/app/script/Shell/checkinpanel/ck_smzdm.js
> at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
> at Function.Module._load (node:internal/modules/cjs/loader:778:27)
> at Module.require (node:internal/modules/cjs/loader:1005:19)
> at require (node:internal/modules/cjs/helpers:94:18)
> at Object.<anonymous> (/usr/local/app/script/Shell/checkinpanel/utils.js:2:15)
> at Module._compile (node:internal/modules/cjs/loader:1101:14)
> at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
> at Module.load (node:internal/modules/cjs/loader:981:32)
> at Function.Module._load (node:internal/modules/cjs/loader:822:12)
> at Module.require (node:internal/modules/cjs/loader:1005:19) {
> code: 'MODULE_NOT_FOUND',
> requireStack: [
> '/usr/local/app/script/Shell/checkinpanel/utils.js',
> '/usr/local/app/script/Shell/checkinpanel/ck_smzdm.js'
> ]
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/3370587/137611349-538d755a-c080-4411-8095-d4c6ea5313eb.png)

全局安装疑似存在问题，请先使用 `npm install got json5 request -cwd script/Shell/checkinpanel` 尝试

**Comment by tanmx** [comment]
@Oreomeow 取消全局安装可以了

![image](https://user-images.githubusercontent.com/3370587/137611633-e79101a2-f212-419b-bb2e-3a8cb7fefd72.png)

**Comment by mjyhj** [comment]
PY版能正常跑，JS版报错，推送显示
没有读取到什么值得买有效cookie，请访问zhiyou.smzdm.com进行登录
![1](https://user-images.githubusercontent.com/22577418/141666084-38c0ddb3-6a8a-4f04-bc8a-ce8511cbbd72.png)

**Comment by Oreomeow** [comment]
@mjyhj 运行签到依赖任务即可

**Comment by mjyhj** [comment]
> @mjyhj 运行签到依赖任务即可

已经运行过的，全部安装成功的

**Comment by Oreomeow** [comment]
@mjyhj 贴一下依赖安装的日志

**Comment by Oreomeow** [comment]
已解决，报错原因为旧版青龙有新版青龙的子文件夹，依赖安装在子文件夹中而报错，解决方法是删除子文件夹或更新新版青龙

**Comment by Deleted-Account** [comment]
请教一下SMZDM的多账号应该怎么填
变成小白看了下TOML的语法
以为是
[[SMZDM.1]]
cookie = "sess=xxxxxx;"
[[SMZDM.2]]
cookie = "sess=xxxxxx;"
没成功

**Comment by WangMaoren98** [comment]
> 
不用加12
######### 多账号示例 #########
[[SMZDM]]
cookie = "sess=xxxxxx;"
[[SMZDM]]
cookie = "sess=xxxxxx;"

**Comment by WangMaoren98** [comment]
> 请教一下SMZDM的多账号应该怎么填 编程小白看了下TOML的语法 以为是 [[SMZDM.1]] cookie = "sess=xxxxxx;" [[SMZDM.2]] cookie = "sess=xxxxxx;" 没成功

不用加12
######### 多账号示例 #########
[[SMZDM]]
cookie = "sess=xxxxxx;"
[[SMZDM]]
cookie = "sess=xxxxxx;"

**Comment by Deleted-Account** [comment]
> > 请教一下SMZDM的多账号应该怎么填 编程小白看了下TOML的语法 以为是 [[SMZDM.1]] cookie = "sess=xxxxxx;" [[SMZDM.2]] cookie = "sess=xxxxxx;" 没成功
> 
> 不用加12 ######### 多账号示例 ######### [[SMZDM]] cookie = "sess=xxxxxx;" [[SMZDM]] cookie = "sess=xxxxxx;"

---

好的，感谢！~
