### ISSUE TITLE
老哥，bark推送不出来

### ISSUE THREAD

**Issue by SG121** [Oreomeow/checkinpanel#24]
```sh
## 开始执行... 2021-10-11 17:51:00

Exception in thread bark:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/ql/scripts/notify_mtr.py", line 119, in bark
    params += f"{bark_params[pair[0]]}={pair[1]}&"
KeyError: 'BARK_PUSH'
尝试检查运行环境...
成功，当前环境为: 青龙面板。
环境检查结束。

配置文件 (notify.json5) 检查开始...
在 /ql/config/notify.json5 发现配置文件。
配置文件检查结束。

通知配置文件存在：/ql/config/notify.json5。
checkinpanel 当前版本：20211010-2-022，不在 8-12 点内，跳过版本检查。

配置文件 (check.json5) 检查开始...
在 /ql/config/check.json5 发现配置文件。
配置文件检查结束。

每日签到: 已签到
用户昵称: 
每日打卡: 天
积分总计: 0
微博钱包: 已签到
当前现金: 0.73 元

每日签到: 已签到
用户昵称: 
每日打卡: 天
积分总计: 0
微博钱包: 已签到
当前现金: 2.30 元


bark 服务启动
微博

每日签到: 已签到
用户昵称: 
每日打卡: 天
积分总计: 0
微博钱包: 已签到
当前现金: 0.73 元

每日签到: 已签到
用户昵称: 
每日打卡: 天
积分总计: 0
微博钱包: 已签到
当前现金: 2.30 元



时间很贪婪——有时候，它会独自吞噬所有的细节。    ----追风筝的人

## 执行结束... 2021-10-11 17:51:09 耗时 9 秒
```

**Comment by Oreomeow** [comment]
BARK 推送变量由 `BARK` 变为 `BARK_PUSH`

**Comment by SG121** [comment]
@Oreomeow @night-raise   我把文件全删了重新拉的也不行，推不出来
