### ISSUE TITLE
青龙 smzdm 签到错误

### ISSUE THREAD

**Issue by EchoChan314** [Oreomeow/checkinpanel#33]
TypeError: Cannot read property 'body' of undefined
    at Object.adapterHttpResponse (/ql/scripts/utils.js:17:12039)
    at Request._callback (/ql/scripts/utils.js:17:12663)
    at self.callback (/ql/scripts/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.start (/ql/scripts/node_modules/request/request.js:753:10)
    at Request.end (/ql/scripts/node_modules/request/request.js:1505:10)
    at end (/ql/scripts/node_modules/request/request.js:564:14)
    at Immediate.<anonymous> (/ql/scripts/node_modules/request/request.js:578:7)
    at processImmediate (internal/timers.js:464:21)

已经按照https://github.com/Oreomeow/checkinpanel#2-%E5%AE%89%E8%A3%85%E4%BE%9D%E8%B5%96 安装了依赖，拉取命令是ql repo https://github.com/Oreomeow/checkinpanel.git "ins_|ck_smzdm" "^checkin" "^notify|^utils" "master" py版的可以执行，但是js版的不能，不知道啥原因。签到依赖也已经拉取执行了。

**Comment by Oreomeow** [comment]
```text
什么值得买


========== [Cookie 1] Start ========== 
签到！恭喜您抽中1碎银子，更多福利尽在生活频道~
积分0 经验2405( 67) 金币0
碎银子29( 1) 未读消息27
点值 7/7 去购买 12/12
点赞 7/7 收藏 7/7
用户近期经验变动情况(有延迟)：
刚刚 收藏文章  8经验值
刚刚 收藏文章  8经验值
刚刚 收藏文章  8经验值
刚刚 收藏文章  8经验值
刚刚 收藏文章  8经验值
22分钟前 点赞文章  3经验值
22分钟前 点赞文章  3经验值
22分钟前 点赞文章  3经验值
22分钟前 点赞文章  3经验值
22分钟前 点赞文章  3经验值
31分钟前 每日登录  1经验值
42分钟前 好价文章打分  3经验值
42分钟前 好价文章打分  3经验值
43分钟前 好价文章打分  3经验值
43分钟前 每日签到  2经验值
16小时前 好价文章打分  3经验值
16小时前 好价文章打分  3经验值
16小时前 好价文章打分  3经验值
11-03 01:46 每日登录  1经验值
11-03 00:52 点赞文章  3经验值
如经验值无变动，请更新Cookie。
========== [Cookie 1]  End  ========== 




GitHub: https://github.com/Oreomeow/checkinpanel
```

暂时不清楚，不影响实际运行

**Comment by Oreomeow** [comment]
#21
