### ISSUE TITLE
一言接口挂了 开了一言直接所有都不通知了 建议异常处理一下

### ISSUE THREAD

**Issue by lustime** [Oreomeow/checkinpanel#36]

**Comment by night-raise** [comment]
请提供必要的截图和异常说明。

**Comment by lustime** [comment]
> 请提供必要的截图和异常说明。
现在没问题了 接口好了，这是之前报错
    return self.read(nbytes, buffer)
68
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
69
    return self._sslobj.read(len, buffer)
70
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
71
​
72
During handling of the above exception, another exception occurred:
73
​
74
Traceback (most recent call last):
75
  File "Oreomeow_checkinpanel_master_ck_smzdm.py", line 88, in <module>
76
    send("什么值得买", res)
77
  File "/ql/scripts/notify_mtr.py", line 536, in send
78
    text = one() if hitokoto else ""
79
  File "/ql/scripts/notify_mtr.py", line 481, in one
80
    res = requests.get(url).json()
81
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 76, in get
82
    return request('get', url, params=params, **kwargs)
83
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
84
    return session.request(method=method, url=url, **kwargs)
85
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
86
    resp = self.send(prep, **send_kwargs)
87
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
88
    r = adapter.send(request, **kwargs)
89
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
90
    raise ConnectionError(err, request=request)
91
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
92
​
93
## 执行结束... 2021-11-06 16:53:58 耗时 16 秒
94
​

**Comment by wzwcc** [comment]
@lustime 这是你网络问题把。。。

**Comment by lustime** [comment]
> @lustime 这是你网络问题把。。。

https://v1.hitokoto.cn/ 下午那会4g都访问不了了。现在好了

**Comment by wzwcc** [comment]
@lustime

**Comment by night-raise** [comment]
已经增加异常处理。
