### ISSUE TITLE
qinglong  V2.10.2  运行 签到依赖 报 error

### ISSUE THREAD

**Issue by Se7enMuting** [Oreomeow/checkinpanel#40]
运行 签到依赖 报 error

```
## 开始执行... 2021-11-11 16:49:15

fetch https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
v3.14.2-127-g0195433b93 [https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.14/main]
v3.14.2-130-g25ed5c1be6 [https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.14/community]
OK: 14942 distinct packages available
bash 已安装
curl 已安装
gcc 已安装
git 已安装
jq 已安装
libffi-dev 已安装
musl-dev 已安装
openssl-dev 已安装
python3 已安装
python3-dev 已安装
py3-pip 已安装
Requirement already satisfied: pip in /usr/lib/python3.9/site-packages (20.3.4)
Collecting pip
  Downloading pip-21.3.1-py3-none-any.whl (1.7 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.3.4
    Uninstalling pip-20.3.4:
      Successfully uninstalled pip-20.3.4
Successfully installed pip-21.3.1
bs4 已安装
cryptography==3.2.1 已安装
json5 已安装
pyaes 已安装
requests 已安装
rsa 已安装
npm WARN using --force Recommended protections disabled.
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm ERR! Cannot read properties of null (reading 'matches')

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-11-11T08_52_45_028Z-debug.log
.......... npm install axios begin ..........
---------- npm install axios succeed ----------
crypto-js 已安装
got 已安装
npm WARN using --force Recommended protections disabled.
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: content-disposition@0.5.3
npm WARN Found: peer eslint-plugin-import@">=2.13.0" from eslint-config-standard@12.0.0
npm WARN node_modules/.pnpm/content-disposition@0.5.3/node_modules/content-disposition/node_modules/eslint-config-standard
npm WARN   dev eslint-config-standard@"12.0.0" from content-disposition@0.5.3
npm WARN   node_modules/.pnpm/content-disposition@0.5.3/node_modules/content-disposition
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer eslint-plugin-import@">=2.13.0" from eslint-config-standard@12.0.0
npm WARN node_modules/.pnpm/content-disposition@0.5.3/node_modules/content-disposition/node_modules/eslint-config-standard
npm WARN   dev eslint-config-standard@"12.0.0" from content-disposition@0.5.3
npm WARN   node_modules/.pnpm/content-disposition@0.5.3/node_modules/content-disposition
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: content-disposition@0.5.3
npm WARN Found: peer eslint-plugin-node@">=7.0.0" from eslint-config-standard@12.0.0
npm WARN node_modules/.pnpm/content-disposition@0.5.3/node_modules/content-disposition/node_modules/eslint-config-standard
npm WARN   dev eslint-config-standard@"12.0.0" from content-disposition@0.5.3
npm WARN   node_modules/.pnpm/content-disposition@0.5.3/node_modules/content-disposition
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer eslint-plugin-node@">=7.0.0" from eslint-config-standard@12.0.0
npm WARN node_modules/.pnpm/content-disposition@0.5.3/node_modules/content-disposition/node_modules/eslint-config-standard
npm WARN   dev eslint-config-standard@"12.0.0" from content-disposition@0.5.3
npm WARN   node_modules/.pnpm/content-disposition@0.5.3/node_modules/content-disposition
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: mime-types@2.1.34
npm WARN Found: peer eslint-plugin-import@">=2.18.0" from eslint-config-standard@14.1.1
npm WARN node_modules/.pnpm/mime-types@2.1.34/node_modules/mime-types/node_modules/eslint-config-standard
npm WARN   dev eslint-config-standard@"14.1.1" from mime-types@2.1.34
npm WARN   node_modules/.pnpm/mime-types@2.1.34/node_modules/mime-types
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer eslint-plugin-import@">=2.18.0" from eslint-config-standard@14.1.1
npm WARN node_modules/.pnpm/mime-types@2.1.34/node_modules/mime-types/node_modules/eslint-config-standard
npm WARN   dev eslint-config-standard@"14.1.1" from mime-types@2.1.34
npm WARN   node_modules/.pnpm/mime-types@2.1.34/node_modules/mime-types
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm ERR! Cannot read properties of null (reading 'matches')

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-11-11T08_53_31_798Z-debug.log
.......... npm install json5 begin ..........
---------- npm install json5 succeed ----------
npm ERR! code ELSPROBLEMS
npm ERR! invalid: request@2.88.2 /ql/scripts/node_modules/request

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-11-11T08_53_34_212Z-debug.log
request 已安装

## 执行结束... 2021-11-11 16:53:34 耗时 259 秒
```

然后 跑 爱企查 log这个

```
## 开始执行... 2021-11-11 16:50:16

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'axios'
Require stack:
- /ql/scripts/Oreomeow_checkinpanel_master_ck_aqc.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/ql/scripts/Oreomeow_checkinpanel_master_ck_aqc.js:7:15)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/scripts/Oreomeow_checkinpanel_master_ck_aqc.js' ]
}

## 执行结束... 2021-11-11 16:50:16 耗时 0 秒
```

依赖的问题吗？我按照大大的readme，进docker 3条依赖都装了，最后那个运行报error和 签到依赖 报的一样的。。。

**Comment by Se7enMuting** [comment]
qinglong是新开的独立docker，没有和别的库混用，就拉了大大你的库

**Comment by Oreomeow** [comment]
@Se7enMuting 容器内运行 `npm audit fix --force` 进行修复。我研究一下 npm 安装的问题

**Comment by Se7enMuting** [comment]
用 `npm audit fix --force` 还是不行，log如下
```
0 verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'audit',
0 verbose cli   'fix',
0 verbose cli   '--force'
0 verbose cli ]
1 info using npm@8.1.3
2 info using node@v16.13.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 3ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 3ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/ql/.npmrc Completed in 1ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:/root/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 12ms
19 timing npm:load:configload Completed in 12ms
20 timing npm:load:setTitle Completed in 0ms
21 timing npm:load:setupLog Completed in 1ms
22 timing config:load:flatten Completed in 5ms
23 timing npm:load:cleanupLog Completed in 3ms
24 timing npm:load:configScope Completed in 0ms
25 timing npm:load:projectScope Completed in 1ms
26 warn using --force Recommended protections disabled.
27 timing npm:load Completed in 28ms
28 timing arborist:ctor Completed in 3ms
29 timing command:audit Completed in 71ms
30 verbose stack Error: loadVirtual requires existing shrinkwrap file
30 verbose stack     at Arborist.loadVirtual (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-virtual.js:62:18)
30 verbose stack     at async Arborist.audit (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/audit.js:25:18)
30 verbose stack     at async Audit.exec (/usr/local/lib/node_modules/npm/lib/commands/audit.js:62:5)
30 verbose stack     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:67:5)
31 verbose cwd /ql
32 verbose Linux 4.19.0-18-cloud-amd64
33 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "audit" "fix" "--force"
34 verbose node v16.13.0
35 verbose npm  v8.1.3
36 error code ENOLOCK
37 error audit This command requires an existing lockfile.
38 error audit Try creating one first with: npm i --package-lock-only
39 error audit Original error: loadVirtual requires existing shrinkwrap file
40 verbose exit 1
```
暂时改用 elecV2P ，很不习惯，看单个任务的 log 没青龙方便

**Comment by Oreomeow** [comment]
@Se7enMuting @Se7enMuting 青龙依赖安装方式应该很快就会改，敬请期待

**Comment by Oreomeow** [comment]
@Se7enMuting 已更新，可以测试下

**Comment by Se7enMuting** [comment]
好像qinglong那边出问题了。。。我新拉的qinglong镜像直接面板打不开。。。issues里一边在叫。。。这个作者docker hub 里面也没有其他tag。。。等那边稳定了我再试试吧。。。

**Comment by Se7enMuting** [comment]
qinglong退回到2.9.7，用大佬的方法安装依赖没出error，看来是qinglong里面的问题，先这样了，感谢
