### ISSUE TITLE
欢太商城 OPPP商城出错！

### ISSUE THREAD

**Issue by myseil** [Oreomeow/checkinpanel#49]
```sh
尝试检查运行环境...
成功，当前环境为: 青龙面板。
环境检查结束。

配置文件 (notify.toml) 检查开始...
在 /ql/config/notify.toml 发现配置文件。
配置文件检查结束。

通知配置文件存在：/ql/config/notify.toml。
checkinpanel 当前版本：20211118-4-211，不在 8-12 点内，跳过版本检查。

配置文件 (check.toml) 检查开始...
在 /ql/config/check.toml 发现配置文件。
配置文件检查结束。

Traceback (most recent call last):
  File "Oreomeow_checkinpanel_master_ck_heytap.py", line 582, in <module>
    res = Heytap(check_items=_check_items).main()
  File "Oreomeow_checkinpanel_master_ck_heytap.py", line 562, in main
    self.client = self.get_user_info()
  File "Oreomeow_checkinpanel_master_ck_heytap.py", line 85, in get_user_info
    response = self.session.get(
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 317, in prepare
    self.prepare_headers(headers)
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 451, in prepare_headers
    check_header_validity(header)
  File "/usr/lib/python3.8/site-packages/requests/utils.py", line 978, in check_header_validity
    raise InvalidHeader("Invalid return character or leading space in header: %s" % name)
requests.exceptions.InvalidHeader: Invalid return character or leading space in header: User-Agent

## 执行结束... 2021-11-18 21:55:18 耗时 1 秒
```

**Comment by Oreomeow** [comment]
检查配置文件 `check.toml`

```toml
[[HEYTAP]]
cookie = "xxxxxx"
draw = false
useragent = " Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36 Edg/94.0.992.50" // " Mozilla 不能包含空格
```

正确示范如下

```toml
[[HEYTAP]]
cookie = "xxxxxx"
draw = false
useragent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36 Edg/94.0.992.50" // " Mozilla 不能包含空格
```

**Comment by myseil** [comment]
> 检查配置文件 `check.toml`
> 
> ```toml
> [[HEYTAP]]
> cookie = "xxxxxx"
> draw = false
> # " Mozillaxxx" 不能包含空格
> useragent = " Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36 Edg/94.0.992.50"
> ```
> 
> 正确示范如下
> 
> ```toml
> [[HEYTAP]]
> cookie = "xxxxxx"
> draw = false
> useragent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36 Edg/94.0.992.50"
> ```

OKOK  可以关闭了！  确实是空格导致的！
