### ISSUE TITLE
大佬，通知文件还有点问题。

### ISSUE THREAD

**Issue by wingser** [Oreomeow/checkinpanel#50]
【1】通知文件，一个欢太的，config.json5格式不对，这个没错，本来换了toml了吗，我就吧这个文件删了，正常了。
```python traceback
## 开始执行... 2021-11-19 10:42:55

通知配置文件存在：/ql/config/notify.json5。
Traceback (most recent call last):
  File "/ql/scripts/Oreomeow_checkinpanel_master/notify_mtr.py", line 92, in <module>
    for k, v in dict(tomli.load(open(CONFIG_PATH, "rb"))).items():
  File "/usr/lib/python3.8/site-packages/tomli/_parser.py", line 64, in load
    return loads(s, parse_float=parse_float)
  File "/usr/lib/python3.8/site-packages/tomli/_parser.py", line 112, in loads
    raise suffixed_err(src, pos, "Invalid statement")
tomli.TOMLDecodeError: Invalid statement (at line 1, column 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ck_heytap.py", line 16, in <module>
    from notify_mtr import send
  File "/ql/scripts/Oreomeow_checkinpanel_master/notify_mtr.py", line 97, in <module>
    f"错误：配置文件 {check_config} 格式不对，请学习 https://toml.io/cn/v1.0.0\n错误信息：\n{traceback.format_exc()}"
NameError: name 'check_config' is not defined

## 执行结束... 2021-11-19 10:42:58 耗时 3 秒
```

【2】但是运行js的smzdm签到的时候，提示config.json5文件不存在。

```js
🔔sendNotify, 开始!
自行配置路径通知文件读取失败，错误信息： Error: ENOENT: no such file or directory, open '/ql/config/notify.json5'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at getNotifyData
```

这就尴尬了，我是删也不行，留着也不行。

**Comment by Oreomeow** [comment]
@wingser 运行拉库命令，检查文件 utils.js 是否更新到最新，这边没问题

**Comment by wingser** [comment]
卧槽，我知道了，我自己在config.sh里面配置的文件还是config.json5
