### ISSUE TITLE
昨天拉库签到正常，今天就有问题，麻烦看下

### ISSUE THREAD

**Issue by zhouyang2021** [Oreomeow/checkinpanel#52]
```python traceback
Traceback (most recent call last):
  File "/ql/scripts/utils.py", line 37, in get_data
    DATA = tomli.load(open(check_config, "rb"))
  File "/usr/lib/python3.8/site-packages/tomli/_parser.py", line 64, in load
    return loads(s, parse_float=parse_float)
  File "/usr/lib/python3.8/site-packages/tomli/_parser.py", line 123, in loads
    raise suffixed_err(
tomli.TOMLDecodeError: Expected newline or end of document after a statement (at line 86, column 1259)
```

**Comment by Oreomeow** [comment]
@zhouyang2021 配置文件 86 行自己检查，可能是引号
