### ISSUE TITLE
epic 脚本报错：日志是

### ISSUE THREAD

**Issue by FlechazoPh** [Oreomeow/checkinpanel#62]
![image](https://user-images.githubusercontent.com/94276146/145684808-fd543b76-b908-4b42-9853-ed3fb7136d23.png)

![image](https://user-images.githubusercontent.com/94276146/145684805-5767a1e6-8b3d-4171-aa0b-d07d280b9cf1.png)

```python consoled 
尝试检查运行环境...
成功，当前环境为: 青龙面板。
环境检查结束。

配置文件 (notify.toml) 检查开始...
未找到配置文件（不一定是错误），路径为: /ql/config/notify.toml。
配置文件检查结束。

checkinpanel 当前版本：20211211-4-201，不在 8-12 点内，跳过版本检查。

配置文件 (check.toml) 检查开始...
在 /ql/config/check.toml 发现配置文件。
配置文件检查结束。

Traceback (most recent call last):
  File "/ql/scripts/Oreomeow_checkinpanel_master_ck_epic.py", line 1544, in <module>
    start()
  File "/ql/scripts/Oreomeow_checkinpanel_master_ck_epic.py", line 1539, in start
    res = run(args, check_items=_check_items)
  File "/ql/scripts/Oreomeow_checkinpanel_master_ck_epic.py", line 1514, in run
    claimed_item_titles = main(args, raise_error=True)
  File "/ql/scripts/Oreomeow_checkinpanel_master_ck_epic.py", line 1423, in main
    claimer = EpicgamesClaimer(
  File "/ql/scripts/Oreomeow_checkinpanel_master_ck_epic.py", line 347, in __init__
    self.open_browser()
  File "/ql/scripts/Oreomeow_checkinpanel_master_ck_epic.py", line 1144, in open_browser
    return self._loop.run_until_complete(self._open_browser_async())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/ql/scripts/Oreomeow_checkinpanel_master_ck_epic.py", line 395, in _open_browser_async
    self.browser = await launch(
  File "/usr/lib/python3.9/site-packages/pyppeteer/launcher.py", line 307, in launch
    return await Launcher(options, **kwargs).launch()
  File "/usr/lib/python3.9/site-packages/pyppeteer/launcher.py", line 168, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "/usr/lib/python3.9/site-packages/pyppeteer/launcher.py", line 227, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:


## 执行结束... 2021-12-12 00:09:17 耗时 49 秒
```

**Comment by Oreomeow** [comment]
@FlechazoPh 进群交流，标题下方有图标
