### ISSUE TITLE
问题请教，个别脚本 cookie 填写后，运行报错，而且影响其他脚本运行。。。

### ISSUE THREAD

**Issue by Se7enMuting** [Oreomeow/checkinpanel#63]
环境：青龙 2.10.12，运行过` 签到依赖`，

比如我填写[[IQIYI]]的cookie，我按照 sample 的格式和顺序重新组合填写：
```
cookie = "__dfp=xxxxxx; QP0013=xxxxxx; QP0022=xxxxxx; QYABEX=xxxxxx; P00001=xxxxxx; P00002=xxxxxx; P00003=xxxxxx; P00007=xxxxxx; QC163=xxxxxx; QC175=xxxxxx; QC179=xxxxxx; QC170=xxxxxx; P00010=xxxxxx; P00PRU=xxxxxx; P01010=xxxxxx; QC173=xxxxxx; QC180=xxxxxx; P00004=xxxxxx; QP0030=xxxxxx; QC006=xxxxxx; QC007=xxxxxx; QC008=xxxxxx; QC010=xxxxxx; nu=xxxxxx; __uuid=xxxxxx; QC005=xxxxxx;"
```

之后运行报错，如下：

```
## 开始执行... 2021-12-13 21:39:22

/usr/lib/python3.8/site-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.7) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
尝试检查运行环境...
成功，当前环境为: 青龙面板。
环境检查结束。

配置文件 (notify.toml) 检查开始...
在 /ql/config/notify.toml 发现配置文件。
配置文件检查结束。

通知配置文件存在：/ql/config/notify.toml。
checkinpanel 当前版本：20211213-4-010，不在 8-12 点内，跳过版本检查。

配置文件 (check.toml) 检查开始...
在 /ql/config/check.toml 发现配置文件。
配置文件检查结束。

错误：配置文件 /ql/config/check.toml 格式不对，请学习 https://toml.io/cn/v1.0.0
错误信息：
Traceback (most recent call last):
  File "/ql/scripts/Oreomeow_checkinpanel_master/utils.py", line 37, in get_data
    DATA = tomli.load(open(check_config, "rb"))
  File "/usr/lib/python3.8/site-packages/tomli/_parser.py", line 64, in load
    return loads(s, parse_float=parse_float)
  File "/usr/lib/python3.8/site-packages/tomli/_parser.py", line 123, in loads
    raise suffixed_err(
tomli.TOMLDecodeError: Expected newline or end of document after a statement (at line 110, column 183)


## 执行结束... 2021-12-13 21:39:23 耗时 1 秒
```

而且我其他本来运行正常的脚本，比如 百度贴吧，这时也不能正常运行了，报和上面一样的错误
我只有把[[IQIYI]]的cookie改成 `cookie = ""` ，其他本来运行正常的脚步才会恢复正常运行。。
搞不懂这个.toml 格式错误问题在哪里？我哪里没有注意吗？
[[V2EX]]的脚本也有同样问题，填写 cookie 后运行报错，且别人也没办法运行了。。。

**Comment by Oreomeow** [comment]
@Se7enMuting 110 行 183 列，检查单双引号等问题

**Comment by Se7enMuting** [comment]
@Oreomeow [[IQIYI]]的cookie 里有些字段自带双引号，是不是要自己修改？改成单引号？加转义符?

**Comment by Oreomeow** [comment]
@Se7enMuting 看头上的注释啊，写了好几个示例了

**Comment by Se7enMuting** [comment]
@Oreomeow 我看到了，刚转 .toml ，看来.toml 也是有不方便的地方的。。。

**Comment by Se7enMuting** [comment]
所以 .toml 里，默认 cookie 最外层直接全部用单引号应该就没事了。。

**Comment by Oreomeow** [comment]
@Se7enMuting 一般情况下最外层用单引号即可解决 80% 以上问题

**Comment by Oreomeow** [comment]
@Se7enMuting json5 转的默认使用双引号，所以会产生问题
