### ISSUE TITLE
epic脚本异常

### ISSUE THREAD

**Issue by hrj5032188** [Oreomeow/checkinpanel#64]
脚本日志:

```python console
## 开始执行... 2021-12-14 11:18:05

尝试检查运行环境...
成功，当前环境为: 青龙面板。
环境检查结束。

配置文件 (notify.toml) 检查开始...
未找到配置文件（不一定是错误），路径为: /ql/config/notify.toml。
配置文件检查结束。

checkinpanel 当前版本：20211214-4-001，最新版本：20211214-4-001

配置文件 (check.toml) 检查开始...
在 /ql/config/check.toml 发现配置文件。
配置文件检查结束。

[33m[2021-12-14 11:18:46  WARN] CAPTCHA is required for unknown reasons[0m
[33m[2021-12-14 11:18:58  WARN] CAPTCHA is required for unknown reasons[0m
[31m[2021-12-14 11:22:07 ERROR] Failed to claim one item: Waiting for selector "#purchase-app button[class*=confirm]:not([disabled])" failed: timeout 180000ms exceeds.[0m
Traceback (most recent call last):
  File "ck_epic.py", line 1544, in <module>
    start()
  File "ck_epic.py", line 1539, in start
    res = run(args, check_items=_check_items)
  File "ck_epic.py", line 1514, in run
    claimed_item_titles = main(args, raise_error=True)
  File "ck_epic.py", line 1434, in main
    return claimer.run_once(
  File "ck_epic.py", line 1178, in run_once
    return self._loop.run_until_complete(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "ck_epic.py", line 1114, in _run_once_async
    claimed_item_titles = await run_claim()
  File "ck_epic.py", line 1107, in run_claim
    raise PermissionError("Failed to claim some items")
PermissionError: Failed to claim some items

## 执行结束... 2021-12-14 11:22:12 耗时 247 秒
```

**Comment by Oreomeow** [comment]
@hrj5032188 epic 疑似加大了验证力度，看脸
