### ISSUE TITLE
epic最近失效了，领不了

### ISSUE THREAD

**Issue by rikkishi** [Oreomeow/checkinpanel#67]
log如下
## 开始执行... 2021-12-20 09:50:01

# 正在应用 轮换Cookie 模式...
# 当前总共 19 个有效账号，其中前 5 个账号为固定顺序。
# 今天从第 11 个账号开始轮换，轮换频次为：1 个账号/天。
尝试检查运行环境...
成功，当前环境为: 青龙面板。
环境检查结束。

配置文件 (notify.toml) 检查开始...
在 /ql/config/notify.toml 发现配置文件。
配置文件检查结束。

通知配置文件存在：/ql/config/notify.toml。
checkinpanel 当前版本：20211219-4-020，最新版本：20211219-4-020

配置文件 (check.toml) 检查开始...
在 /ql/config/check.toml 发现配置文件。
配置文件检查结束。

[33m[2021-12-20 09:53:48  WARN] Waiting for selector "#webPurchaseContainer iframe" failed: timeout 180000ms exceeds.[0m
[33m[2021-12-20 09:57:05  WARN] Waiting for selector "#webPurchaseContainer iframe" failed: timeout 180000ms exceeds.[0m
[31m[2021-12-20 10:00:22 ERROR] Failed to claim one item: Waiting for selector "#webPurchaseContainer iframe" failed: timeout 180000ms exceeds.[0m
Traceback (most recent call last):
  File "Oreomeow_checkinpanel_master_ck_epic.py", line 1615, in <module>
    start()
  File "Oreomeow_checkinpanel_master_ck_epic.py", line 1610, in start
    res = run(args, check_items=_check_items)
  File "Oreomeow_checkinpanel_master_ck_epic.py", line 1585, in run
    claimed_item_titles = main(args, raise_error=True)
  File "Oreomeow_checkinpanel_master_ck_epic.py", line 1505, in main
    return claimer.run_once(
  File "Oreomeow_checkinpanel_master_ck_epic.py", line 1249, in run_once
    return self._loop.run_until_complete(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "Oreomeow_checkinpanel_master_ck_epic.py", line 1185, in _run_once_async
    claimed_item_titles = await run_claim()
  File "Oreomeow_checkinpanel_master_ck_epic.py", line 1178, in run_claim
    raise PermissionError("Failed to claim some items")
PermissionError: Failed to claim some items

## 执行结束... 2021-12-20 10:00:22 耗时 621 秒

**Comment by LGinC** [comment]
怎么解决的,我的昨儿还行,今儿就报这个错了

**Comment by Oreomeow** [comment]
目前暂只有 docker/云函数 版的有效

https://github.com/luminoleon/epicgames-claimer
