### ISSUE TITLE
EPIC 在elecV2P 下check in失败

### ISSUE THREAD

**Issue by kingsmart1** [Oreomeow/checkinpanel#71]
`[checkin.js error][2021-12-27 21:16:29.465] Traceback (most recent call last):
  File "/usr/local/app/script/Shell/checkinpanel/ck_epic.py", line 1615, in <module>
    start()
  File "/usr/local/app/script/Shell/checkinpanel/ck_epic.py", line 1610, in start
    res = run(args, check_items=_check_items)
  File "/usr/local/app/script/Shell/checkinpanel/ck_epic.py", line 1585, in run
    claimed_item_titles = main(args, raise_error=True)
  File "/usr/local/app/script/Shell/checkinpanel/ck_epic.py", line 1494, in main
    claimer = EpicgamesClaimer(
  File "/usr/local/app/script/Shell/checkinpanel/ck_epic.py", line 363, in __init__
    self.open_browser()
  File "/usr/local/app/script/Shell/checkinpanel/ck_epic.py", line 1215, in open_browser
    return self._loop.run_until_complete(self._open_browser_async())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/app/script/Shell/checkinpanel/ck_epic.py", line 411, in _open_browser_async
    self.browser = await launch(
  File "/usr/lib/python3.9/site-packages/pyppeteer/launcher.py", line 307, in launch
    return await Launcher(options, **kwargs).launch()
  File "/usr/lib/python3.9/site-packages/pyppeteer/launcher.py", line 148, in launch
    self.proc = subprocess.Popen(  # type: ignore
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chromium-browser'
[checkin.js  info][2021-12-27 21:16:29.502] command: python3 ck_epic.py finished`

**Comment by Mr54233** [comment]
青龙也是报这个错

**Comment by umbrellax** [comment]
同问

**Comment by night-raise** [comment]
task Oreomeow_checkinpanel_master/ins_selenium.sh

这个命令执行过吗？

**Comment by LQ2002** [comment]
![image](https://user-images.githubusercontent.com/50812010/147670072-17e53522-542d-449e-8ccf-8235b44675e6.png)
作者你好！运行了这个脚本Oreomeow_checkinpanel_master/ins_selenium.sh，但又有新的问题了。

**Comment by night-raise** [comment]
如果确定自己账号密码没问题，那么可能是脚本出问题了，等猫猫有空更新吧。

**Comment by LQ2002** [comment]
好的

**Comment by 363843342** [comment]
问题+1

**Comment by 363843342** [comment]
<img width="363" alt="屏幕截图 2022-01-03 103641" src="https://user-images.githubusercontent.com/71557954/147896299-f850497f-ec46-4a65-ae01-9a409b08609b.png">
这边除了提示ck_epic.py错误，还提示需要验证码（[33m[2022-01-03 10:32:52  WARN] CAPTCHA is required for unknown reasons when logging in）。然后我把ck_epic.py手动删除，在执行两次拉库指令（ql repo https://github.com/Oreomeow/checkinpanel.git "api_|ck_|ins_" "^checkin" "^notify|^utils|cpm" "master"）

问题好像解决了
<img width="393" alt="image" src="https://user-images.githubusercontent.com/71557954/147896447-358b20a8-a98d-4123-9def-f0dbf641ebd9.png">
我不知道这是为什么但是可能是解决方案，手动删除scripts目录下的Oreomeow_checkinpanel_master目录下的ck_epic.py后重新拉库，可以运气好就解决了

> ![image]作者你好！运行了这个脚本Oreomeow_checkinpanel_master/ins_selenium.sh，但又有新的问题了。

**Comment by night-raise** [comment]
（我自己没用这个，要等失踪人口猫猫看看哈哈哈）

**Comment by Oreomeow** [comment]
上游也因验证问题而失效，暂不更新
